name: ubuntu-22

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: |
          git submodule update --init --recursive
          echo ${{ github.server_url }}
          sudo add-apt-repository -y ppa:kisak/kisak-mesa
          sudo apt update -y
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 14
          sudo apt update -y
          sudo apt-get -y install libwayland-dev wayland-protocols \
          mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev mesa-utils \
          libc++-14-dev libc++abi-14-dev libunwind-14-dev libxkbcommon-dev
          clang++ --version
          cmake --version

      - name: Build Debug Packages
        run: |
          mkdir -p ${{github.workspace}}/build/debug
          CC=/usr/lib/llvm-14/bin/clang CXX=/usr/lib/llvm-14/bin/clang++ cmake \
            -B ${{github.workspace}}/build/debug \
            -D CMAKE_BUILD_TYPE=Debug \
            -D CMAKE_STAGING_PREFIX=${{github.workspace}}/build/staging/usr/local \
            -D BUILD_NUMBER=${GITHUB_RUN_ID} \
            -D LLVM_ROOT=/usr/lib/llvm-14
          make package -j
          ls -la _packages

      - name: Build Release Packages
        run: |
          mkdir -p ${{github.workspace}}/build/release
          CC=/usr/lib/llvm-14/bin/clang CXX=/usr/lib/llvm-14/bin/clang++ cmake \
            -B ${{github.workspace}}/build/release \
            -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_STAGING_PREFIX=${{github.workspace}}/build/staging/usr/local \
            -D BUILD_NUMBER=${GITHUB_RUN_ID} \
            -D LLVM_ROOT=/usr/lib/llvm-14
          make package -j
          ls -la _packages
